[package]
name = "proximo-client"
version = "0.1.0"
authors = ["Martin Garton <garton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["rt-core", "macros"] }
tokio-rustls = "0.12"
tonic = { git = "https://github.com/hyperium/tonic", features = ["tls", "tls-roots"] }

[build-dependencies]
tonic-build = { git = "https://github.com/hyperium/tonic" }
